# Checks for any broken links in markdown files
name: Check Markdown links

on: workflow_call

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-verbose-mode: 'yes'
        config-file: '.github/workflows/markdown-link-check.config.json'

